name: Convoroom Backend
on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: ConvoRoom
  PYTHON_VERSION: "3.12"

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure Web App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django>=4.0
          chmod +x ./install_packages.sh
          ./install_packages.sh

      - name: Create requirements.txt from installed packages
        run: |
          pip freeze > requirements.txt

      - name: Verify Django installation
        run: |
          python -c "import django; print('Django version:', django.get_version())"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
